linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt

linters-settings:
  misspell:
    locale: US

issues:
  exclude-dirs:
    - site
